name: 'Typescript::Check'
description: 'Runs compile and lint actions with Typescript code'
inputs:
  npmAuthToken:
    description: 'NPM token'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
