name: Build Docker Image

on:
  push:
    branches:
      - release/*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: deeepvision/github-action-docker-build@release/1.0
        with:
          name: typescript-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
